language: node_js
# Work-around for https://github.com/travis-ci/travis-ci/issues/8836#issuecomment-356362524.
sudo: required
dist: xenial
addons:
  apt:
    packages:
      # This is required to run new chrome on old trusty
      - libnss3

node_js:
  - 8
  - 7
  - 6

cache:
  directories:
    - ~/.npm

services:
  - xvfb

# allow headful tests
before_install:
  # Enable user namespace cloning
  - "sysctl kernel.unprivileged_userns_clone=1"
  # Launch XVFB
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
